from setuptools import setup, find_packages
setup(
    name='OWR',
    version='2.7.2',
    description='Obscene word recognition package',
    url='https://github.com/RuslanGaliullin/FFixTelegramBot/tree/OWR',
    author='Vlad Vasilev, Ruslan Galiullin',
    author_email='vpvasilev.work@gmail.com, rmgaliullin@edu.hse.ru',
    license='GNU GENERAL PUBLIC LICENSE',
    packages=['OWR'],
    package_data={'': ['data/obscenity_words.json']},
    include_package_data=True,
    install_requires=['scikit-learn',
                      'huggingsound',
                      'librosa',
                      'levenshtein',
                      'soundfile',
                      'fonetika',
                      'numpy',
                      'playsound',
                      'pylcs'],
)
